"""add project_id status index on tasks

Revision ID: 4840454901bd
Revises: 27edc82c2b1b
Create Date: 2026-08-06 14:10:52.985856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4840454901bd"
down_revision: Union[str, None] = "27edc82c2b1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_tasks_project_id_status", "tasks", ["project_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_project_id_status", table_name="tasks")
    # ### end Alembic commands ###
